<?php
/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function movie_portal_preprocess_html(&$variables) {
    // Get current node url.
    $node_url = \Drupal::request()->getRequestUri();
    
    // Check whether the node url is of required node or not.
    if ($node_url === '/movies') {

      // Attach the custom_theme/custom-render library to the page.
      $variables['#attached']['library'][] = 'movie_portal/movie-render';
    }
  }
?>